import Colors from 'src/constants/colors';

const DEFAULT_ACTIVE_COLOR_LINE_WIDTH = 2;
const DEFAULT_INDEX_INITIAL_LAT_LNG = 0;
const DEFAULT_CREATED_NEW_POLYGON = false;
const DEFAULT_BACKGROUND_VIEW_CANVAS = 'rgba(0, 0, 0, 0)';
const DEFAULT_FILL_BACKGROUND_CANVAS = 'rgba(0, 0, 0, 0)';
const DEFAULT_ACTIVE_COLOR_LINE = Colors.primaryBlack;
const DEFAULT_UNIT_DISTANCE = 'm';
const DEFAULT_DRAW_MODE = false;

export {
  DEFAULT_ACTIVE_COLOR_LINE_WIDTH,
  DEFAULT_FILL_BACKGROUND_CANVAS,
  DEFAULT_BACKGROUND_VIEW_CANVAS,
  DEFAULT_INDEX_INITIAL_LAT_LNG,
  DEFAULT_CREATED_NEW_POLYGON,
  DEFAULT_ACTIVE_COLOR_LINE,
  DEFAULT_UNIT_DISTANCE,
  DEFAULT_DRAW_MODE,
};
