export const API_START = 'API_START';
export const API_FINISH = 'API_FINISH';
export const SET_ONBOARDING_ACTION = 'SET_ONBOARDING_ACTION';

export const GET_MIN_APP_VERSION = 'GET_MIN_APP_VERSION';
export const GET_MIN_APP_VERSION_SUCCESS = 'GET_MIN_APP_VERSION_SUCCESS';
export const GET_MIN_APP_VERSION_ERROR = 'GET_MIN_APP_VERSION_ERROR';

export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_ERROR = 'USER_LOGOUT_ERROR';

export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';

export const USER_SIGNUP = 'USER_SIGNUP';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_ERROR = 'USER_SIGNUP_ERROR';

export const GET_POPULAR_LOCATION = 'GET_POPULAR_LOCATION';
export const GET_POPULAR_LOCATION_SUCCESS = 'GET_POPULAR_LOCATION_SUCCESS';
export const GET_POPULAR_LOCATION_ERROR = 'GET_POPULAR_LOCATION_ERROR';

export const SET_APP_IS_OPEN = 'SET_APP_IS_OPEN';
export const SET_APP_IS_OPEN_SUCCESS = 'SET_APP_IS_OPEN_SUCCESS';
export const SET_APP_IS_OPEN_ERROR = 'SET_APP_IS_OPEN_ERROR';

export const SEND_USERS_FEEDBACK = 'SEND_USERS_FEEDBACK';
export const SEND_USERS_FEEDBACK_SUCCESS = 'SEND_USERS_FEEDBACK_SUCCESS';
export const SEND_USERS_FEEDBACK_ERROR = 'SEND_USERS_FEEDBACK_ERROR';

export const SET_APP_METRICS = 'SET_APP_METRICS';

export const GET_MEASURE_RATES = 'GET_MEASURE_RATES';
export const GET_MEASURE_RATES_SUCCESS = 'GET_MEASURE_RATES_SUCCESS';
export const GET_MEASURE_RATES_ERROR = 'GET_MEASURE_RATES_ERROR';

// Search
export const UPDATE_SEARCH = 'UPDATE_SEARCH';
export const UPDATE_SEARCH_QUERY = 'UPDATE_SEARCH_QUERY';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';
export const CLEAR_SEARCH_RANGE = 'CLEAR_SEARCH_RANGE';
export const PARTIAL_SEARCH_CLEAR = 'PARTIAL_SEARCH_CLEAR';

export const SEARCH_PROPERTIES = 'SEARCH_PROPERTIES';
export const SEARCH_PROPERTIES_SUCCESS = 'SEARCH_PROPERTIES_SUCCESS';
export const SEARCH_PROPERTIES_MAP_SUCCESS = 'SEARCH_PROPERTIES_MAP_SUCCESS';
export const SEARCH_PROPERTIES_ERROR = 'SEARCH_PROPERTIES_ERROR';

export const SEARCH_PROPERTIES_COUNT_SUCCESS = 'SEARCH_PROPERTIES_COUNT_SUCCESS';

export const GET_PROPERTY_USER = 'GET_PROPERTY_USER';
export const GET_PROPERTY_USER_SUCCESS = 'GET_PROPERTY_USER_SUCCESS';
export const GET_PROPERTY_USER_ERROR = 'GET_PROPERTY_USER_ERROR';
export const SEND_PROPERTY_CLAIM = 'SEND_PROPERTY_CLAIM';
export const SEND_PROPERTY_CLAIM_SUCCESS = 'SEND_PROPERTY_CLAIM_SUCCESS';
export const SEND_PROPERTY_CLAIM_ERROR = 'SEND_PROPERTY_CLAIM_ERROR';
export const GET_PROPERTY_DETAILS = 'GET_PROPERTY_DETAILS';
export const GET_PROPERTY_DETAILS_SUCCESS = 'GET_PROPERTY_DETAILS_SUCCESS';
export const GET_PROPERTY_DETAILS_ERROR = 'GET_PROPERTY_DETAILS_ERROR';
export const SEARCH_RANGES_SUCCESS = 'SEARCH_RANGES_SUCCESS';

//Profile
export const LOAD_PROFILE = 'LOAD_PROFILE';
export const LOAD_PROFILE_SUCCESS = 'LOAD_PROFILE_SUCCESS';
export const LOAD_PROFILE_ERROR = 'LOAD_PROFILE_ERROR';

export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

export const GET_PROPERTIES = 'GET_PROPERTIES';
export const GET_PROPERTIES_SUCCESS = 'GET_PROPERTIES_SUCCESS';
export const GET_PROPERTIES_ERROR = 'GET_PROPERTIES_ERROR';
export const RESET_PROPERTIES = 'RESET_PROPERTIES';

export const GET_FAVOURITE_PROPERTIES = 'GET_FAVOURITE_PROPERTIES';
export const GET_FAVOURITE_PROPERTIES_SUCCESS = 'GET_FAVOURITE_PROPERTIES_SUCCESS';
export const GET_FAVOURITE_PROPERTIES_ERROR = 'GET_FAVOURITE_PROPERTIES_ERROR';

export const LIKE_PROPERTY = 'LIKE_PROPERTY';
export const LIKE_PROPERTY_SUCCESS = 'LIKE_PROPERTY_SUCCESS';
export const LIKE_PROPERTY_ERROR = 'LIKE_PROPERTY_ERROR';

export const UNLIKE_PROPERTY = 'UNLIKE_PROPERTY';
export const UNLIKE_PROPERTY_SUCCESS = 'UNLIKE_PROPERTY_SUCCESS';
export const UNLIKE_PROPERTY_ERROR = 'UNLIKE_PROPERTY_ERROR';

export const REMOVE_PROFILE = 'REMOVE_PROFILE';
export const REMOVE_PROFILE_SUCCESS = 'REMOVE_PROFILE_SUCCESS';
export const REMOVE_PROFILE_ERROR = 'REMOVE_PROFILE_ERROR';

export const FETCH_FAQ_SETTINGS = 'FETCH_FAQ_SETTINGS';
export const FETCH_FAQ_SETTINGS_SUCCESS = 'FETCH_FAQ_SETTINGS_SUCCESS';
export const FETCH_FAQ_SETTINGS_ERROR = 'FETCH_FAQ_SETTINGS_ERROR';

export const UPLOAD_AVATAR = 'UPLOAD_AVATAR';
export const UPLOAD_AVATAR_SUCCESS = 'UPLOAD_AVATAR_SUCCESS';
export const UPLOAD_AVATAR_ERROR = 'UPLOAD_AVATAR_ERROR';

export const CHANGE_PHONE_NUMBER = 'CHANGE_PHONE_NUMBER';
export const CHANGE_PHONE_NUMBER_SUCCESS = 'CHANGE_PHONE_NUMBER_SUCCESS';
export const CHANGE_PHONE_NUMBER_ERROR = 'CHANGE_PHONE_NUMBER_ERROR';

export const UPDATE_NOTIFICATION_SETTINGS = 'UPDATE_NOTIFICATION_SETTINGS';
export const UPDATE_NOTIFICATION_SETTINGS_SUCCESS = 'UPDATE_NOTIFICATION_SETTINGS_SUCCESS';
export const UPDATE_NOTIFICATION_SETTINGS_ERROR = 'UPDATE_NOTIFICATION_SETTINGS_ERROR';

export const GET_NOTIFICATION_SETTINGS = 'GET_NOTIFICATION_SETTINGS';
export const GET_NOTIFICATION_SETTINGS_SUCCESS = 'GET_NOTIFICATION_SETTINGS_SUCCESS';
export const GET_NOTIFICATION_SETTINGS_ERROR = 'GET_NOTIFICATION_SETTINGS_ERROR';

// Properties
export const UPDATE_CURRENT_PROPERTY = 'UPDATE_CURRENT_PROPERTY';
export const SAVE_PROPERTY = 'SAVE_PROPERTY';
export const SAVE_PROPERTY_SUCCESS = 'SAVE_PROPERTY_SUCCESS';
export const SAVE_PROPERTY_ERROR = 'SAVE_PROPERTY_ERROR';

export const SET_PROPERTY_FIlTER = 'SET_PROPERTY_FIlTER';

export const DELETE_PROPERTY = 'DELETE_PROPERTY';
export const DELETE_PROPERTY_SUCCESS = 'DELETE_PROPERTY_SUCCESS';
export const DELETE_PROPERTY_ERROR = 'DELETE_PROPERTY_ERROR';

export const RESET_CURRENT_PROPERTY = 'RESET_CURRENT_PROPERTY';

export const UPLOAD_PROPERTY_PHOTOS = 'UPLOAD_PROPERTY_PHOTOS';
export const UPLOAD_PROPERTY_PHOTOS_SUCCESS = 'UPLOAD_PROPERTY_PHOTOS_SUCCESS';
export const UPLOAD_PROPERTY_PHOTOS_ERROR = 'UPLOAD_PROPERTY_PHOTOS_ERROR';

export const SEND_EMAIL_TO_SUPPORT = 'SEND_EMAIL_TO_SUPPORT';
export const SEND_EMAIL_TO_SUPPORT_SUCCESS = 'SEND_EMAIL_TO_SUPPORT_SUCCESS';
export const SEND_EMAIL_TO_SUPPORT_ERROR = 'SEND_EMAIL_TO_SUPPORT_ERROR';

// NOTIFICATION

export const SAVE_FCM_TOKEN = 'SAVE_FCM_TOKEN';
export const SAVE_FCM_TOKEN_SUCCESS = 'SAVE_FCM_TOKEN_SUCCESS';
export const SAVE_FCM_TOKEN_ERROR = 'SAVE_FCM_TOKEN_ERROR';

// Inbox

export const SEND_CHAT_CLAIM = 'SEND_CHAT_CLAIM';
export const SEND_CHAT_CLAIM_SUCCESS = 'SEND_CHAT_CLAIM_SUCCESS';
export const SEND_CHAT_CLAIM_ERROR = 'SEND_CHAT_CLAIM_ERROR';

// Chats

export const GET_MY_CHATS = 'GET_MY_CHATS';
export const GET_MY_CHATS_SUCCESS = 'GET_MY_CHATS_SUCCESS';
export const GET_MY_CHATS_ERROR = 'GET_MY_CHATS_ERROR';

export const GET_OTHER_CHATS = 'GET_OTHER_CHATS';
export const GET_OTHER_CHATS_SUCCESS = 'GET_OTHER_CHATS_SUCCESS';
export const GET_OTHER_CHATS_ERROR = 'GET_OTHER_CHATS_ERROR';

export const GET_CHATS = 'GET_CHATS';
export const SET_RECIVED_MESSAGE = 'SET_RECIVED_MESSAGE';
export const SET_RECIVED_REPLIE = 'SET_RECIVED_REPLIE';
export const SET_PENDING_MESSAGE = 'SET_PENDING_MESSAGE';
export const GET_CHATS_MESSAGES = 'GET_CHATS_MESSAGES';
export const GET_CHATS_MESSAGES_SUCCESS = 'GET_CHATS_MESSAGES_SUCCESS';
export const CLEAR_CHAT_MESSAGES = 'CLEAR_CHAT_MESSAGES';

export const DELETE_CHATS = 'DELETE_CHATS';
export const DELETE_CHATS_SUCCESS = 'DELETE_CHATS_SUCCESS';
export const DELETE_CHATS_ERROR = 'DELETE_CHATS_ERROR';

export const PIN_CHATS = 'PIN_CHATS';
export const PIN_CHATS_SUCCESS = 'PIN_CHATS_SUCCESS';
export const PIN_CHATS_ERROR = 'PIN_CHATS_ERROR';

export const UNPIN_CHATS = 'UNPIN_CHATS';
export const UNPIN_CHATS_SUCCESS = 'UNPIN_CHATS_SUCCESS';
export const UNPIN_CHATS_ERROR = 'UNPIN_CHATS_ERROR';

export const MUTE_CHATS = 'MUTE_CHATS';
export const MUTE_CHATS_SUCCESS = 'MUTE_CHATS_SUCCESS';
export const MUTE_CHATS_ERROR = 'MUTE_CHATS_ERROR';

export const UNMUTE_CHATS = 'UNMUTE_CHATS';
export const UNMUTE_CHATS_SUCCESS = 'UNMUTE_CHATS_SUCCESS';
export const UNMUTE_CHATS_ERROR = 'UNMUTE_CHATS_ERROR';

export const READ_ALL_MSG = 'READ_ALL_MSG';
export const READ_ALL_MSG_SUCCESS = 'READ_ALL_MSG_SUCCESS';
export const READ_ALL_MSG_ERROR = 'READ_ALL_MSG_ERROR';

export const SET_CURRENT_CHAT = 'SET_CURRENT_CHAT';

export const CLEAR_CURRENT_CHAT = 'CLEAR_CURRENT_CHAT';
